// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1743502700);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1743502700);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1743502700);
user_pref("app.update.lastUpdateTime.region-update-timer", 1743502700);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1743502700);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1743502700);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1743502730);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1743502700);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{46dd4553-0654-441a-ab5f-cf3382034312}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1743502670);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 143);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"2343089779872775\":1743502881655,\"1671074653680199\":1743502881660,\"8719161747387704\":1743502881660}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{0a9c2f95-42ec-49c4-9797-fa7bc67e9865}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1743502671);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1743502718090");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1743504540090");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1743502674077");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1743524274077");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1743502671");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20240419214016");
user_pref("browser.startup.homepage_override.mstone", "125.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1743502671);
user_pref("browser.topsites.contile.lastFetch", 1743502971);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1743502671524");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "125.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "95feff87bfd947db85ea86690a7761c2");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1743502700);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20240419214016");
user_pref("extensions.lastAppVersion", "125.0.2");
user_pref("extensions.lastPlatformVersion", "125.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"4076be9b-9933-4522-a751-052de6d29d4f\",\"pictureinpicture@mozilla.org\":\"133c0af0-2ec6-48a8-ad41-cd92e8a7114c\",\"screenshots@mozilla.org\":\"f883c440-3331-4a6e-b9fb-c01bd97a606a\",\"webcompat-reporter@mozilla.org\":\"f229d176-3142-4674-bcf4-8ee269d18b17\",\"webcompat@mozilla.org\":\"c895b3d3-149a-4d59-9e78-85b72087eca0\",\"default-theme@mozilla.org\":\"9b711e70-6f87-471c-b1dc-6a1d00a5056a\",\"addons-search-detection@mozilla.com\":\"5682e5c4-490a-4552-8491-010768989b90\",\"google@search.mozilla.org\":\"e3b4a745-32b2-4c17-9ea8-6463a3b292d1\",\"wikipedia@search.mozilla.org\":\"49caa0ef-3519-4988-97a2-9d8fba0aa5bf\",\"bing@search.mozilla.org\":\"5b2ab588-d6af-4554-820e-850604420ddc\",\"ddg@search.mozilla.org\":\"0f8a627e-f63f-4772-90b5-a89d96a75570\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1743503548);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: 2152398861, errorCode: 2, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1743502790);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1743502790);
user_pref("media.gmp-manager.buildID", "20240419214016");
user_pref("media.gmp-manager.lastCheck", 1743502790);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1743503548);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1743503548911");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "9369dc63-4c0a-4b48-859d-51158cdf4714");
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_update_seconds", 1743502790);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1743502790);
user_pref("services.settings.main.devtools-devices.last_check", 1743502790);
user_pref("services.settings.main.hijack-blocklists.last_check", 1743502790);
user_pref("services.settings.main.language-dictionaries.last_check", 1743502790);
user_pref("services.settings.main.nimbus-desktop-experiments.last_check", 1743502699);
user_pref("services.settings.main.password-recipes.last_check", 1743502790);
user_pref("services.settings.main.search-config-overrides-v2.last_check", 1743502790);
user_pref("services.settings.main.search-config-overrides.last_check", 1743502790);
user_pref("services.settings.main.search-config.last_check", 1743502790);
user_pref("services.settings.main.sites-classification.last_check", 1743502790);
user_pref("services.settings.main.translations-identification-models.last_check", 1743502790);
user_pref("services.sync.engine.addresses.available", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1743503548);
user_pref("toolkit.startup.last_success", 1743502669);
user_pref("toolkit.telemetry.cachedClientID", "8e428a07-0247-4735-9c4f-71927dd54d32");
user_pref("toolkit.telemetry.previousBuildID", "20240419214016");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
